// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wumgwtgnhzwyerunztuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bWd3dGduaHp3eWVydW56dHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNzE5NzMsImV4cCI6MjA4NzY0Nzk3M30.fkb7SnXqEUns6cA7yCOpEoyw7qsqU4dkZybEamDnzmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});